- name: ec2instance-playbook
  hosts: host
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400

    - name: Create keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker GPG key
      command: curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker-archive-keyring.gpg

    - name: Set permissions for Docker GPG key
      file:
        path: /etc/apt/keyrings/docker-archive-keyring.gpg
        mode: '0644'

    - name: Add Docker Repository
      shell: echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true

    - name: Install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Ensure Docker service is started
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Create a Docker network using shell
      shell: docker network create test

    - name: Re-create a MySQL container using shell
      shell: |
        docker run --name quanghuy-mysql --network test --network-alias test \
        -e MYSQL_ROOT_PASSWORD=12345 -e MYSQL_DATABASE=Planny \
        -p 3306:3306 -d mysql:8.0

    - name: Copy SQL script with owner and permissions
      ansible.builtin.copy:
        src: ./script
        dest: /home/ubuntu/script
        owner: ubuntu
        group: ubuntu

    - name: Sleep to ensure MySQL container is ready
      shell: sleep 15

    - name: Execute SQL script in MySQL container
      shell: docker exec -i quanghuy-mysql mysql --user=root --password=12345 < /home/ubuntu/script

    - name: Re-create a Spring Boot container using shell
      shell: |
        docker run --name quanghuy-springboot --network test --network-alias test \
        -p 8080:8080 -d huynq201104/springboot

    - name: Prune unused Docker objects
      shell: docker system prune -af
